public class AccountTriggerDispatcher {

    public static void dispatch(System.TriggerOperation operationType){
        switch on operationType{
            WHEN BEFORE_INSERT{

            }
            WHEN AFTER_INSERT{

            }
            WHEN BEFORE_UPDATE{

            }
            WHEN AFTER_UPDATE{

            }
            WHEN BEFORE_DELETE{

            }
            WHEN AFTER_DELETE{

            }
            WHEN AFTER_UNDELETE{

            }
            WHEN ELSE{

            }
        }
    }
}